version: '3'
services:
        web:
                image: hacks_project_flask
                build: .
                ports:
                        - "8091:8080"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped
